// <auto-generated />
namespace Sodra.SqlClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sodra_0002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sodra_0002));
        
        string IMigrationMetadata.Id
        {
            get { return "201604131051194_Sodra_0002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
